project_id = "bjyzysgtbuyreplvltur"

[functions.admin-users]
verify_jwt = false

[functions.validate-google-login]
verify_jwt = false

[functions.login-senha]
verify_jwt = false

[functions.push-config]
verify_jwt = false

[functions.send-push]
verify_jwt = false
